name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [armhf, arm64]

    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/asssaf/picore-tryboot
          tags: "type=raw,value=latest,priority=2000"

      - name: Build and push builder image
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          platforms: linux/amd64
          target: export
          build-args: |
            ARCH=${{ matrix.arch }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: "type=tar,dest=${{github.workspace}}/tryboot.tar"

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: tryboot-${{matrix.arch}}.tgz
          path: "${{github.workspace}}/tryboot.tar"
